#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : mvn-scalatest_2.12
Version  : 1
Release  : 1
URL      : https://repo.maven.apache.org/maven2/org/scalatest/scalatest_2.12/3.0.3/scalatest_2.12-3.0.3.jar
Source0  : https://repo.maven.apache.org/maven2/org/scalatest/scalatest_2.12/3.0.3/scalatest_2.12-3.0.3.jar
Source1  : https://repo.maven.apache.org/maven2/org/scalatest/scalatest_2.12/3.0.3/scalatest_2.12-3.0.3.pom
Summary  : No detailed summary available
Group    : Development/Tools
License  : Apache-2.0
Requires: mvn-scalatest_2.12-data = %{version}-%{release}

%description
No detailed description available

%package data
Summary: data components for the mvn-scalatest_2.12 package.
Group: Data

%description data
data components for the mvn-scalatest_2.12 package.


%prep

%build

%install
mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/scalatest/scalatest_2.12/3.0.3
cp %{SOURCE0} %{buildroot}/usr/share/java/.m2/repository/org/scalatest/scalatest_2.12/3.0.3/scalatest_2.12-3.0.3.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/scalatest/scalatest_2.12/3.0.3
cp %{SOURCE1} %{buildroot}/usr/share/java/.m2/repository/org/scalatest/scalatest_2.12/3.0.3/scalatest_2.12-3.0.3.pom


%files
%defattr(-,root,root,-)

%files data
%defattr(-,root,root,-)
/usr/share/java/.m2/repository/org/scalatest/scalatest_2.12/3.0.3/scalatest_2.12-3.0.3.jar
/usr/share/java/.m2/repository/org/scalatest/scalatest_2.12/3.0.3/scalatest_2.12-3.0.3.pom
