#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : mvn-scalatest_2.12
Version  : 1
Release  : 4
URL      : https://repo.maven.apache.org/maven2/org/scalatest/scalatest_2.12/3.0.3/scalatest_2.12-3.0.3.jar
Source0  : https://repo.maven.apache.org/maven2/org/scalatest/scalatest_2.12/3.0.3/scalatest_2.12-3.0.3.jar
Source1  : https://repo.maven.apache.org/maven2/org/scalatest/scalatest_2.12/3.0.0/scalatest_2.12-3.0.0.jar
Source2  : https://repo.maven.apache.org/maven2/org/scalatest/scalatest_2.12/3.0.0/scalatest_2.12-3.0.0.pom
Source3  : https://repo.maven.apache.org/maven2/org/scalatest/scalatest_2.12/3.0.3/scalatest_2.12-3.0.3.jar
Source4  : https://repo.maven.apache.org/maven2/org/scalatest/scalatest_2.12/3.0.3/scalatest_2.12-3.0.3.pom
Source5  : https://repo.maven.apache.org/maven2/org/scalatest/scalatest_2.12/3.0.3/scalatest_2.12-3.0.3.pom
Summary  : No detailed summary available
Group    : Development/Tools
License  : Apache-2.0
Requires: mvn-scalatest_2.12-data = %{version}-%{release}

%description
No detailed description available

%package data
Summary: data components for the mvn-scalatest_2.12 package.
Group: Data

%description data
data components for the mvn-scalatest_2.12 package.


%prep
%setup -q -n META-INF

%build

%install
mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/scalatest/scalatest_2.12/3.0.3
cp %{SOURCE0} %{buildroot}/usr/share/java/.m2/repository/org/scalatest/scalatest_2.12/3.0.3/scalatest_2.12-3.0.3.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/scalatest/scalatest_2.12/3.0.0
cp %{SOURCE1} %{buildroot}/usr/share/java/.m2/repository/org/scalatest/scalatest_2.12/3.0.0/scalatest_2.12-3.0.0.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/scalatest/scalatest_2.12/3.0.0
cp %{SOURCE2} %{buildroot}/usr/share/java/.m2/repository/org/scalatest/scalatest_2.12/3.0.0/scalatest_2.12-3.0.0.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/scalatest/scalatest_2.12/3.0.3
cp %{SOURCE3} %{buildroot}/usr/share/java/.m2/repository/org/scalatest/scalatest_2.12/3.0.3/scalatest_2.12-3.0.3.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/scalatest/scalatest_2.12/3.0.3
cp %{SOURCE4} %{buildroot}/usr/share/java/.m2/repository/org/scalatest/scalatest_2.12/3.0.3/scalatest_2.12-3.0.3.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/scalatest/scalatest_2.12/3.0.3
cp %{SOURCE5} %{buildroot}/usr/share/java/.m2/repository/org/scalatest/scalatest_2.12/3.0.3/scalatest_2.12-3.0.3.pom


%files
%defattr(-,root,root,-)

%files data
%defattr(-,root,root,-)
/usr/share/java/.m2/repository/org/scalatest/scalatest_2.12/3.0.0/scalatest_2.12-3.0.0.jar
/usr/share/java/.m2/repository/org/scalatest/scalatest_2.12/3.0.0/scalatest_2.12-3.0.0.pom
/usr/share/java/.m2/repository/org/scalatest/scalatest_2.12/3.0.3/scalatest_2.12-3.0.3.jar
/usr/share/java/.m2/repository/org/scalatest/scalatest_2.12/3.0.3/scalatest_2.12-3.0.3.pom
